"use strict";
let places = ['italy', 'germany', 'Agra', 'Eifel towers', 'time square'];
console.log('orignal ' + places);
console.log('copy ' + [...places].sort());
console.log('orignal' + places);
console.log('copy ' + [...places].sort().reverse());
console.log(places.reverse());
console.log(places.reverse());
console.log(places.sort());
console.log(places.sort().reverse());
